name: Install SUPER-PRINT
description: An action to install SUPER-PRINT
inputs:
  msg:
    required: true

runs:
  using: composite
  steps:
    - name: Install & run super-print
      shell: bash
      run: |
        echo "pwned"